"""Render chat sessions as Markdown, DOCX, or PDF."""
from __future__ import annotations

import io
import re
from datetime import datetime, timezone
from typing import Any, List

from markupsafe import escape as html_escape

_MAX_MESSAGES = 500


def _extract_citations(messages: List[Any]) -> list[dict]:
    """Collect unique citations across all messages."""
    seen: set[int] = set()
    citations: list[dict] = []
    for msg in messages:
        raw = msg.citations
        if not raw or not isinstance(raw, list):
            continue
        for c in raw:
            if not isinstance(c, dict):
                continue
            idx = c.get("ref_index", 0)
            if idx not in seen:
                seen.add(idx)
                citations.append(c)
    return sorted(citations, key=lambda c: c.get("ref_index", 0))


def _format_footnote(c: dict) -> str:
    page = c.get("page", "?")
    doc = c.get("document_filename", "")
    snippet = c.get("text_snippet", "")[:80]
    source = f"{doc}, " if doc else ""
    return f"Page {page}, {source}\"{snippet}...\""


def render_markdown(title: str, doc_name: str, messages: List[Any]) -> str:
    if len(messages) > _MAX_MESSAGES:
        raise ValueError(f"Export limited to {_MAX_MESSAGES} messages")

    lines = [
        f"# {title}",
        f"*Document: {doc_name}*",
        f"*Exported: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
        "",
        "---",
        "",
    ]

    for msg in messages:
        if msg.role == "user":
            lines.append(f"**Q:** {msg.content}")
        else:
            text = re.sub(r"\[(\d+)\]", r"[^\1]", msg.content)
            lines.append(f"**A:** {text}")
        lines.append("")

    citations = _extract_citations(messages)
    if citations:
        lines.append("---")
        lines.append("## References")
        lines.append("")
        for c in citations:
            idx = c.get("ref_index", 0)
            lines.append(f"[^{idx}]: {_format_footnote(c)}")

    lines.extend(["", "---", "*Generated by DocTalk — www.doctalk.site*"])
    return "\n".join(lines)


class ExportError(Exception):
    """Raised when export rendering fails."""


def render_docx(title: str, doc_name: str, messages: List[Any]) -> io.BytesIO:
    if len(messages) > _MAX_MESSAGES:
        raise ValueError(f"Export limited to {_MAX_MESSAGES} messages")

    try:
        from docx import Document
    except ImportError:
        raise ExportError("DOCX export is not available: python-docx not installed")
    from docx.shared import Pt, RGBColor

    doc = Document()
    doc.add_heading(title, level=1)
    p = doc.add_paragraph()
    run = p.add_run(
        f"Document: {doc_name} | Exported: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
    )
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(128, 128, 128)

    for msg in messages:
        if msg.role == "user":
            p = doc.add_paragraph()
            run = p.add_run(f"Q: {msg.content}")
            run.bold = True
        else:
            doc.add_paragraph(msg.content)

    citations = _extract_citations(messages)
    if citations:
        doc.add_heading("References", level=2)
        for c in citations:
            idx = c.get("ref_index", 0)
            doc.add_paragraph(f"[{idx}] {_format_footnote(c)}", style="List Number")

    p = doc.add_paragraph()
    run = p.add_run("Generated by DocTalk — www.doctalk.site")
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(160, 160, 160)

    try:
        buf = io.BytesIO()
        doc.save(buf)
        buf.seek(0)
        return buf
    except Exception as e:
        raise ExportError(f"DOCX rendering failed: {e}") from e


def render_pdf(title: str, doc_name: str, messages: List[Any]) -> io.BytesIO:
    if len(messages) > _MAX_MESSAGES:
        raise ValueError(f"Export limited to {_MAX_MESSAGES} messages")

    try:
        from weasyprint import HTML
    except (ImportError, OSError):
        raise ExportError("PDF export is not available: weasyprint not installed or system libraries missing")

    safe_title = html_escape(title)
    safe_doc = html_escape(doc_name)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    msg_html = []
    for msg in messages:
        safe_content = html_escape(msg.content)
        if msg.role == "user":
            msg_html.append(f'<div class="q"><strong>Q:</strong> {safe_content}</div>')
        else:
            msg_html.append(f'<div class="a">{safe_content}</div>')

    citations = _extract_citations(messages)
    refs_html = ""
    if citations:
        refs_items = []
        for c in citations:
            idx = c.get("ref_index", 0)
            refs_items.append(f"<li>[{idx}] {html_escape(_format_footnote(c))}</li>")
        refs_html = f'<h2>References</h2><ol>{"".join(refs_items)}</ol>'

    html_str = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body {{ font-family: 'Noto Sans CJK SC', 'Noto Sans', sans-serif; font-size: 11pt; color: #333; margin: 2cm; }}
  h1 {{ font-size: 18pt; margin-bottom: 4pt; }}
  .meta {{ color: #888; font-size: 9pt; margin-bottom: 16pt; }}
  .q {{ background: #f5f5f5; padding: 8pt; margin: 6pt 0; border-radius: 4pt; }}
  .a {{ padding: 8pt; margin: 6pt 0; }}
  h2 {{ font-size: 13pt; margin-top: 20pt; }}
  ol {{ font-size: 9pt; color: #666; }}
  .footer {{ text-align: center; color: #aaa; font-size: 8pt; margin-top: 30pt; }}
</style></head><body>
<h1>{safe_title}</h1>
<div class="meta">Document: {safe_doc} | Exported: {date_str}</div>
{"".join(msg_html)}
{refs_html}
<div class="footer">Generated by DocTalk &mdash; www.doctalk.site</div>
</body></html>"""

    try:
        buf = io.BytesIO()
        HTML(string=html_str).write_pdf(buf)
        buf.seek(0)
        return buf
    except Exception as e:
        raise ExportError(f"PDF rendering failed: {e}") from e
