#!/usr/bin/env python3
"""Map DocTalk product surfaces to concrete QA evidence.

This audit does not run product tests. It checks that the current long-running
QA corpus has explicit evidence for each discovered route/API surface and each
objective axis, while preserving open blockers instead of turning coverage into
a false completion signal.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--inventory",
        default=".collab/tasks/qa-route-inventory-2026-05-10.json",
        help="Route inventory JSON generated by qa_route_inventory.js.",
    )
    parser.add_argument("--json-out", required=True)
    return parser.parse_args()


def load_json(relative: str) -> dict[str, Any]:
    path = ROOT / relative
    return json.loads(path.read_text(encoding="utf-8"))


def file_status(relative: str) -> str | None:
    path = ROOT / relative
    if not path.exists() or path.suffix != ".json":
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        return f"load_error:{type(exc).__name__}"
    return str(data.get("status") or data.get("result") or data.get("mode") or "")


def artifact(relative: str) -> dict[str, Any]:
    path = ROOT / relative
    return {
        "path": relative,
        "exists": path.exists(),
        "status": file_status(relative),
    }


EVIDENCE: dict[str, list[str]] = {
    "route_inventory": [
        ".collab/tasks/qa-route-inventory-2026-05-10.json",
        ".collab/tasks/qa-route-inventory-2026-05-10.md",
        ".collab/tasks/qa-route-http-2026-05-10.json",
        ".collab/tasks/qa-route-http-2026-05-10.md",
    ],
    "public_page_regression": [
        ".collab/tasks/qa-run-2026-05-11-production-current-public-regression.md",
        ".collab/tasks/qa-post-deploy-public-regression-production-current-2026-05-11.json",
        ".collab/tasks/qa-run-2026-05-11-production-current-demo-reader-ux.md",
        ".collab/tasks/qa-production-current-demo-reader-ux-2026-05-11.json",
    ],
    "public_static_metadata_links_a11y_perf": [
        ".collab/tasks/qa-run-2026-05-11-production-current-public-regression.md",
        ".collab/tasks/qa-post-deploy-public-regression-production-current-2026-05-11.json",
        ".collab/tasks/qa-run-2026-05-11-production-public-performance-smoke.md",
        ".collab/tasks/qa-production-public-performance-smoke-2026-05-11.json",
    ],
    "contact_form": [
        ".collab/tasks/qa-run-2026-05-11-production-contact-form-ux.md",
        ".collab/tasks/qa-production-contact-form-ux-2026-05-11.json",
    ],
    "tools_ux": [
        ".collab/tasks/qa-run-2026-05-11-production-tools-ux.md",
        ".collab/tasks/qa-production-tools-ux-2026-05-11.json",
    ],
    "auth_pages": [
        ".collab/tasks/qa-run-2026-05-10-browser-auth-admin-ux.md",
        ".collab/tasks/qa-browser-auth-admin-ux-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-11-auth-provider-availability-ux.md",
        ".collab/tasks/qa-auth-provider-availability-ux-after-provider-fix-2026-05-11.json",
        ".collab/tasks/qa-run-2026-05-11-production-auth-provider-availability-ux.md",
        ".collab/tasks/qa-production-auth-provider-availability-ux-2026-05-11.json",
    ],
    "admin": [
        ".collab/tasks/qa-run-2026-05-10-browser-auth-admin-ux.md",
        ".collab/tasks/qa-browser-auth-admin-ux-2026-05-10.json",
    ],
    "billing": [
        ".collab/tasks/qa-run-2026-05-10-billing-credits-matrix.md",
        ".collab/tasks/qa-billing-credits-matrix-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-10-stripe-hosted-browser.md",
        ".collab/tasks/qa-browser-stripe-hosted-ux-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-10-refund-review-workflow.md",
        ".collab/tasks/qa-run-2026-05-11-production-payment-public-sanity-rerun.md",
    ],
    "collections": [
        ".collab/tasks/qa-run-2026-05-10-collections-matrix.md",
        ".collab/tasks/qa-collections-matrix-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-10-browser-app-workflows-ux.md",
        ".collab/tasks/qa-browser-app-workflows-ux-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-11-browser-structured-workflows-ux.md",
        ".collab/tasks/qa-browser-structured-workflows-ux-after-consent-fix-2026-05-11.json",
    ],
    "document-diff": [
        ".collab/tasks/qa-run-2026-05-10-document-diff-matrix.md",
        ".collab/tasks/qa-document-diff-matrix-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-11-document-diff-live-llm.md",
        ".collab/tasks/qa-document-diff-live-llm-2026-05-11.json",
        ".collab/tasks/qa-run-2026-05-11-browser-document-diff-result-ux.md",
        ".collab/tasks/qa-run-2026-05-11-browser-document-diff-polling-ux.md",
    ],
    "profile": [
        ".collab/tasks/qa-run-2026-05-10-account-privacy-matrix.md",
        ".collab/tasks/qa-account-privacy-matrix-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-10-browser-app-workflows-ux.md",
        ".collab/tasks/qa-browser-app-workflows-ux-2026-05-10.json",
    ],
    "reader": [
        ".collab/tasks/qa-run-2026-05-10-browser-reader-export-ux.md",
        ".collab/tasks/qa-browser-reader-export-ux-after-key-fix-2026-05-10.json",
        ".collab/tasks/qa-browser-live-rag-citation-ux-2026-05-11.json",
        ".collab/tasks/qa-run-2026-05-11-production-current-demo-reader-ux.md",
        ".collab/tasks/qa-production-current-demo-reader-ux-2026-05-11.json",
    ],
    "sharing": [
        ".collab/tasks/qa-run-2026-05-10-browser-sharing-ux.md",
        ".collab/tasks/qa-browser-sharing-ux-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-10-browser-chat-share-ux.md",
        ".collab/tasks/qa-browser-chat-share-ux-2026-05-10.json",
    ],
    "frontend_api_guards": [
        ".collab/tasks/qa-run-2026-05-11-production-frontend-api-guards.md",
        ".collab/tasks/qa-production-frontend-api-guards-2026-05-11.json",
    ],
    "backend_document_api": [
        ".collab/tasks/qa-run-2026-05-10-backend-golden-path.md",
        ".collab/tasks/qa-backend-golden-path-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-11-production-document-entry-guards.md",
        ".collab/tasks/qa-production-document-entry-guards-2026-05-11.json",
    ],
    "rag_pdf": [
        ".collab/tasks/qa-run-2026-05-11-private-live-rag.md",
        ".collab/tasks/qa-live-chat-rag-local-upload-deepseek-2026-05-11.json",
        ".collab/tasks/qa-run-2026-05-11-live-rag-corpus-sample.md",
        ".collab/tasks/qa-live-rag-corpus-sample-after-harness-fix-2026-05-11.json",
        ".collab/tasks/qa-run-2026-05-11-live-rag-full-corpus-plan.md",
        ".collab/tasks/qa-live-rag-multi-prompt-full-corpus-plan-2026-05-11.json",
    ],
    "rag_nonpdf": [
        ".collab/tasks/qa-run-2026-05-11-live-rag-nonpdf-plan.md",
        ".collab/tasks/qa-live-rag-nonpdf-plan-2026-05-11.json",
        ".collab/tasks/qa-run-2026-05-11-multiformat-api-golden-path.md",
        ".collab/tasks/qa-multiformat-api-golden-path-2026-05-11.json",
    ],
    "url_import": [
        ".collab/tasks/qa-run-2026-05-10-url-import.md",
        ".collab/tasks/qa-url-import-matrix-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-11-url-edge-matrix.md",
        ".collab/tasks/qa-url-edge-matrix-after-no-text-fix-2026-05-11.json",
        ".collab/tasks/qa-live-chat-rag-local-url-deepseek-after-short-chunk-fix-2026-05-11.json",
    ],
    "test_inputs": [
        ".collab/tasks/qa-corpus-inventory-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-10-corpus-parse-full.md",
        ".collab/tasks/qa-corpus-parse-full-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-11-live-rag-corpus-sample.md",
        ".collab/tasks/qa-live-rag-corpus-sample-after-harness-fix-2026-05-11.json",
        ".collab/tasks/qa-live-rag-multi-prompt-full-corpus-plan-2026-05-11.json",
    ],
    "structured_outputs": [
        ".collab/tasks/qa-run-2026-05-11-structured-workflows-matrix.md",
        ".collab/tasks/qa-structured-workflows-matrix-2026-05-11.json",
        ".collab/tasks/qa-run-2026-05-11-browser-structured-workflows-ux.md",
        ".collab/tasks/qa-browser-structured-workflows-ux-after-consent-fix-2026-05-11.json",
        ".collab/tasks/qa-run-2026-05-11-live-structured-outputs.md",
        ".collab/tasks/qa-live-structured-outputs-blocked-no-env-2026-05-11.json",
    ],
    "locales": [
        ".collab/tasks/qa-run-2026-05-10-locale-ui-smoke.md",
        ".collab/tasks/qa-locale-ui-smoke-after-csp-fix-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-11-authenticated-locale-i18n-cleanup.md",
        ".collab/tasks/qa-authenticated-locale-ui-after-i18n-quality-fix-2026-05-11.json",
    ],
    "permissions": [
        ".collab/tasks/qa-run-2026-05-10-access-boundary.md",
        ".collab/tasks/qa-access-boundary-2026-05-10.json",
        ".collab/tasks/qa-run-2026-05-11-production-anonymous-api-guards.md",
        ".collab/tasks/qa-production-anonymous-api-guards-2026-05-11.json",
        ".collab/tasks/qa-run-2026-05-11-production-internal-auth-guards.md",
        ".collab/tasks/qa-production-internal-auth-guards-2026-05-11.json",
    ],
}


PUBLIC_KINDS = {"public", "seo-public", "seo-content"}


def evidence_refs(keys: list[str]) -> list[dict[str, Any]]:
    refs: list[dict[str, Any]] = []
    seen: set[str] = set()
    for key in keys:
        for item in EVIDENCE[key]:
            if item not in seen:
                refs.append(artifact(item))
                seen.add(item)
    return refs


def area_key(area: str) -> str | None:
    if area in {"admin", "billing", "collections", "document-diff", "profile"}:
        return area
    if area == "reader":
        return "reader"
    if area == "sharing":
        return "sharing"
    return None


def route_surface(route: dict[str, Any]) -> dict[str, Any]:
    keys = ["route_inventory"]
    risks: list[str] = []
    status = "covered"
    kind = route["kind"]
    area = route["area"]

    if kind in PUBLIC_KINDS:
        keys.extend(["public_page_regression", "public_static_metadata_links_a11y_perf"])
        status = "covered_with_open_production_drift"
        risks.append("Current production public regression still has deploy-drift failures/warnings; local fixes require deploy/retest.")
        if area == "demo":
            keys.extend(["rag_pdf", "reader"])
        if area == "contact":
            keys.append("contact_form")
        if area == "tools":
            keys.append("tools_ux")
        if route["route"] in {"/", "/privacy", "/use-cases/healthcare"} or route["route"].startswith("/blog/"):
            risks.append("This route family is in the current production drift set for CSP, fragments, links, or heading-order advisories.")
    elif kind == "auth":
        keys.append("auth_pages")
    elif kind == "gated":
        key = area_key(area)
        if key:
            keys.append(key)
            status = "covered_local_fixture"
        else:
            status = "uncovered"
            risks.append("No area-specific evidence mapping for gated route.")
    else:
        status = "needs_review"
        risks.append(f"Unhandled route kind: {kind}")

    return {
        "route": route["route"],
        "template": route.get("template"),
        "kind": kind,
        "area": area,
        "status": status,
        "risks": risks,
        "evidence": evidence_refs(keys),
    }


def dynamic_surface(template: dict[str, Any]) -> dict[str, Any]:
    route = template["route"]
    if route in {"/blog/[slug]", "/blog/category/[category]", "/demo/[sample]"}:
        keys = ["route_inventory", "public_page_regression", "public_static_metadata_links_a11y_perf"]
        if route == "/demo/[sample]":
            keys.extend(["rag_pdf", "reader"])
        status = "expanded_concrete_routes_covered_with_open_production_drift"
        risks = ["This dynamic template is expanded into concrete routes by the inventory; current production public drift still needs deploy/retest."]
    elif route == "/d/[documentId]":
        keys = ["reader", "backend_document_api", "rag_pdf"]
        status = "covered_with_open_production_drift"
        risks = ["Current production demo direct citation highlight fails until local reader fix is deployed/retested."]
    elif route == "/collections/[collectionId]":
        keys = ["collections", "structured_outputs"]
        status = "covered_local_fixture"
        risks = []
    elif route == "/shared/[token]":
        keys = ["sharing"]
        status = "covered_local_fixture"
        risks = []
    else:
        keys = ["route_inventory"]
        status = "uncovered"
        risks = ["No dynamic-template evidence mapping."]
    return {
        "route": route,
        "area": template["area"],
        "requires": template.get("requires"),
        "status": status,
        "risks": risks,
        "evidence": evidence_refs(keys),
    }


def api_surface(route: dict[str, Any]) -> dict[str, Any]:
    api_route = route["route"]
    keys = ["frontend_api_guards"]
    status = "covered"
    risks: list[str] = []
    if api_route == "/api/proxy/[...path]":
        keys.extend(["backend_document_api", "permissions"])
    elif api_route == "/api/auth/[...nextauth]":
        keys.append("auth_pages")
        status = "covered_except_successful_oauth_email_callback"
        risks.append("Provider UI and guards are covered; successful OAuth/email callback remains externally blocked.")
    elif api_route == "/api/upload-token":
        keys.append("permissions")
    return {
        "route": api_route,
        "area": route["area"],
        "requires": route.get("requires"),
        "status": status,
        "risks": risks,
        "evidence": evidence_refs(keys),
    }


def objective_axis(
    key: str,
    label: str,
    status: str,
    evidence_keys: list[str],
    gaps: list[str],
) -> dict[str, Any]:
    return {
        "key": key,
        "label": label,
        "status": status,
        "evidence": evidence_refs(evidence_keys),
        "gaps": gaps,
    }


def build_objective_axes() -> list[dict[str, Any]]:
    return [
        objective_axis(
            "all_pages_top_down",
            "Top-down page inventory and public/gated route coverage",
            "partial_open_production_drift",
            ["route_inventory", "public_page_regression", "auth_pages", "admin", "billing", "collections", "document-diff", "profile"],
            ["Production deploy/retest remains required for public drift; successful OAuth/email callback is not covered."],
        ),
        objective_axis(
            "all_functions",
            "Primary app functions across ingest, reader, sharing, collections, diff, structured outputs, billing, auth, APIs",
            "partial",
            ["backend_document_api", "url_import", "reader", "sharing", "collections", "document-diff", "structured_outputs", "billing", "permissions", "contact_form", "tools_ux"],
            ["Browser-orchestrated real worker document-diff remains blocked by local server/provider prerequisites."],
        ),
        objective_axis(
            "pdf_document_chat",
            "PDF/document chat answer, citation, persistence, and retrieval quality",
            "partial_blocked",
            ["rag_pdf", "reader", "backend_document_api"],
            ["Full-corpus 239-prompt live RAG matrix is plan-only until normal provider config is available."],
        ),
        objective_axis(
            "citation_jump",
            "Citation jump/highlight across PDF, URL/TextViewer, non-PDF, converted PDFs, and long PDFs",
            "partial_open_production_drift",
            ["reader", "rag_pdf", "url_import", "rag_nonpdf"],
            ["Current production demo direct citation highlight fails desktop/mobile until deploy/retest."],
        ),
        objective_axis(
            "url_reading",
            "URL import, URL edge cases, URL live RAG, and URL citation UX",
            "partial",
            ["url_import"],
            ["Fully live URL/TextViewer browser citation with normal provider config still needs broader coverage."],
        ),
        objective_axis(
            "test_inputs",
            "test_inputs inventory, parse, representative live RAG, retrieval matrix, and full-corpus plan",
            "partial_blocked",
            ["test_inputs", "rag_pdf"],
            ["Full-corpus answer-quality execution remains blocked by provider configuration."],
        ),
        objective_axis(
            "corner_cases_user_pain",
            "Edge inputs, plan limits, deleted/duplicate docs, consent/banner friction, and user error states",
            "partial",
            ["url_import", "backend_document_api", "billing", "collections", "reader", "sharing", "contact_form", "tools_ux"],
            ["More real private-upload LLM result screens and broader user prompt families remain useful follow-up."],
        ),
        objective_axis(
            "accuracy_completeness",
            "Functional accuracy and answer completeness",
            "partial_blocked",
            ["rag_pdf", "rag_nonpdf", "structured_outputs"],
            ["Non-PDF live RAG and structured-output live quality remain blocked by provider configuration."],
        ),
        objective_axis(
            "frontend_ui_ux",
            "Frontend UI/UX across desktop/mobile, public pages, app workflows, reader, and payment handoffs",
            "partial_open_production_drift",
            ["public_page_regression", "public_static_metadata_links_a11y_perf", "contact_form", "tools_ux", "reader", "auth_pages", "billing", "collections", "document-diff", "sharing", "locales"],
            ["Production public drift and demo direct citation bug require frontend deploy/retest."],
        ),
        objective_axis(
            "performance",
            "Performance smoke and workflow timing evidence",
            "covered_smoke_only",
            ["public_static_metadata_links_a11y_perf", "rag_pdf"],
            ["Repeated preview/production runs and real-user-monitoring-style data are not covered."],
        ),
        objective_axis(
            "permissions_security",
            "Auth boundaries, anonymous guards, internal guards, and rate-limit contracts",
            "covered",
            ["permissions", "frontend_api_guards"],
            [],
        ),
        objective_axis(
            "billing",
            "Billing, credits, Stripe test-mode/webhook/hosted handoff, and public production sanity",
            "partial_blocked",
            ["billing"],
            ["Authenticated production Checkout/Portal and external refund-review operations require safe account/business approval."],
        ),
        objective_axis(
            "locales",
            "11-locale public and authenticated UI smoke",
            "covered_ui_partial_rag",
            ["locales", "rag_pdf"],
            ["Broader multilingual private-upload RAG/chat/citation runs remain partial."],
        ),
    ]


def summarize(items: list[dict[str, Any]]) -> dict[str, int]:
    out: dict[str, int] = {}
    for item in items:
        out[item["status"]] = out.get(item["status"], 0) + 1
    return out


def main() -> int:
    args = parse_args()
    inventory = load_json(args.inventory)
    concrete = [route_surface(item) for item in inventory["concrete"]]
    dynamic = [dynamic_surface(item) for item in inventory["dynamicTemplates"]]
    api = [api_surface(item) for item in inventory["apiRoutes"]]
    axes = build_objective_axes()

    missing_evidence = []
    for section_name, section in [("concrete_routes", concrete), ("dynamic_templates", dynamic), ("api_routes", api), ("objective_axes", axes)]:
        for item in section:
            for ref in item["evidence"]:
                if not ref["exists"]:
                    missing_evidence.append({
                        "section": section_name,
                        "surface": item.get("route") or item.get("key"),
                        "path": ref["path"],
                    })

    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "inventory": args.inventory,
        "complete": False,
        "completion_reason": "Coverage evidence exists for discovered surfaces, but objective axes still have provider, deployment, OAuth/email, and safe-production-payment blockers.",
        "summary": {
            "concrete_routes": len(concrete),
            "dynamic_templates": len(dynamic),
            "api_routes": len(api),
            "objective_axes": len(axes),
            "concrete_route_statuses": summarize(concrete),
            "dynamic_template_statuses": summarize(dynamic),
            "api_route_statuses": summarize(api),
            "objective_axis_statuses": summarize(axes),
            "uncovered_concrete_routes": len([item for item in concrete if item["status"] == "uncovered"]),
            "uncovered_dynamic_templates": len([item for item in dynamic if item["status"] == "uncovered"]),
            "uncovered_api_routes": len([item for item in api if item["status"] == "uncovered"]),
            "missing_evidence_artifacts": len(missing_evidence),
        },
        "missing_evidence": missing_evidence,
        "concrete_routes": concrete,
        "dynamic_templates": dynamic,
        "api_routes": api,
        "objective_axes": axes,
    }

    out = ROOT / args.json_out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(
        "SURFACE_COVERAGE_AUDIT complete={complete} routes={routes} dynamic={dynamic} api={api} axes={axes} missing_evidence={missing}".format(
            complete=str(report["complete"]).lower(),
            routes=len(concrete),
            dynamic=len(dynamic),
            api=len(api),
            axes=len(axes),
            missing=len(missing_evidence),
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
